name: Update Hugging Face Stats

on:
  # 每天 UTC 时间 00:00 运行一次 (可以根据需要修改)
  schedule:
    - cron: '0 0 * * *'
  # 允许手动触发
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      # 第一步：检出你的仓库代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 第二步：设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # 可指定你需要的 Python 版本

      # 第三步：安装依赖库
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install huggingface_hub

      # 第四步：运行我们的 Python 脚本
      - name: Run script to update stats
        run: python scripts/update_hf_stats.py

      # 第五步：提交更新后的数据文件
      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'CI: Update Hugging Face stats'
          file_pattern: 'hf_stats.json' 
          commit_user_name: 'github-actions[bot]'
          commit_user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_author: 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>'